const firebaseConfig = {
  apiKey: "AIzaSyDV6YCH-knnBtoCdvT1Z2wEkOU9y_NF_IU",
  authDomain: "phuketfood-a4623.firebaseapp.com",
  databaseURL: "https://phuketfood-a4623.firebaseio.com",
  projectId: "phuketfood-a4623",
  storageBucket: "phuketfood-a4623.appspot.com",
  messagingSenderId: "590945091329",
  appId: "1:590945091329:web:b0fdf7026b087cb8cc6500",
  measurementId: "G-2MDJF4T26J"
};


firebase.initializeApp(firebaseConfig);
firebase.analytics();

var db = firebase.firestore();
var menu=[
  {
    "id_Type": "t_001",
    "id_Meat": "m_009",
    "chinese_Name": "冬阴功汤",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1dT9vz85m7aqblXP9wgRfCZFtkIqPMzcg",
    "id_Menu": "m_001"
  },
  {
    "id_Type": "t_002",
    "id_Meat": "m_009",
    "chinese_Name": "泰式炒河粉",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1cBxLxfGk-71XSgtZsBfztJxrOuLh43H6",
    "id_Menu": "m_002"
  },
  {
    "id_Type": "t_002",
    "id_Meat": "m_001",
    "chinese_Name": "粿条",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1L3dnvt2fNVRsD2ggeEpbO3bGzI_sqq0L",
    "id_Menu": "m_003"
  },
  {
    "id_Type": "t_003",
    "id_Meat": "m_009",
    "chinese_Name": "凉拌木瓜丝",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1GEsqLCUNZRlcA3zN-FFj8op4iX0mS72_",
    "id_Menu": "m_004"
  },
  {
    "id_Type": "t_004",
    "id_Meat": "m_002",
    "chinese_Name": "腰果鸡肉",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1a8FMo154dkPVDOVkH-hAjKEEKPXkYXFk",
    "id_Menu": "m_005"
  },
  {
    "id_Type": "t_005",
    "id_Meat": "m_002",
    "chinese_Name": "绿咖喱鸡",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "very spicy",
    "picture": "https://drive.google.com/open?id=1X5m9jDrKpjx8VeJrJf4nSmY0qlF9vziO",
    "id_Menu": "m_006"
  },
  {
    "id_Type": "t_001",
    "id_Meat": "m_002",
    "chinese_Name": "椰汁鸡汤",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1izrtFpiXI4W1eoFfhOlJi6Mwi1esN7kv",
    "id_Menu": "m_007"
  },
  {
    "id_Type": "t_004",
    "id_Meat": "m_002",
    "chinese_Name": "炒饭",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=16KWnCPy3r8Yuq2x8-pWMuniDhQC-TI_u",
    "id_Menu": "m_008"
  },
  {
    "id_Type": "t_005",
    "id_Meat": "m_003",
    "chinese_Name": "马沙文咖喱",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1OlQpOtx0D24TKU9fjzCyJEf_rhwlg2cg",
    "id_Menu": "m_009"
  },
  {
    "id_Type": "t_004",
    "id_Meat": "m_002",
    "chinese_Name": "鸡饭",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1VCOm4GRShgrUL6lW5fh_mYlzHFKZWFzn",
    "id_Menu": "m_010"
  },
  {
    "id_Type": "t_004",
    "id_Meat": "m_002",
    "chinese_Name": "脆皮三层肉饭",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1grNabg6LxLJ37vl_mR-OgJr5Q8nnftHT",
    "id_Menu": "m_011"
  },
  {
    "id_Type": "t_001",
    "id_Meat": "m_004",
    "chinese_Name": "鱼清汤",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1F3zRxKLpR_5WyZhvJ-GkuKU64cMM5x6A",
    "id_Menu": "m_012"
  },
  {
    "id_Type": "t_004",
    "id_Meat": "m_004",
    "chinese_Name": "菠萝炒饭",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1bKarz3h8Gi_08YJvMRz6vEftO1rLS64T",
    "id_Menu": "m_013"
  },
  {
    "id_Type": "t_004",
    "id_Meat": "m_001",
    "chinese_Name": "猪脚饭",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1RkpB8DxYM3MuYeTAqrTDQyi4_Up7yom7",
    "id_Menu": "m_014"
  },
  {
    "id_Type": "t_004",
    "id_Meat": "m_009",
    "chinese_Name": "芒果糯米饭",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=10Q-tjzX9loW5ZbJ-aQWUFoaFRGRUoDyo",
    "id_Menu": "m_015"
  },
  {
    "id_Type": "t_009",
    "id_Meat": "m_009",
    "chinese_Name": "椰子冰淇淋",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1ev9OQlBbkxfAQxp5hdf9BvgqI6atg395",
    "id_Menu": "m_016"
  },
  {
    "id_Type": "t_010",
    "id_Meat": "m_009",
    "chinese_Name": "水果沙冰",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1EwYmpftC_mTraWPbvBny0LLB2JV1i9Pl",
    "id_Menu": "m_017"
  },
  {
    "id_Type": "t_009",
    "id_Meat": "m_009",
    "chinese_Name": "榴莲雪糕",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1zKLFrv6DfdhAyoEE2m58BCktaTelEZVv",
    "id_Menu": "m_018"
  },
  {
    "id_Type": "t_010",
    "id_Meat": "m_009",
    "chinese_Name": "泰式奶茶",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1tnGoVM0kraSgB0dYzIKaTHDD9C-PMd-N",
    "id_Menu": "m_019"
  },
  {
    "id_Type": "t_006",
    "id_Meat": "m_001",
    "chinese_Name": "烤猪肉",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1NnlJKmkrr0VRxi4G-5sDM9DPRVupEs5M",
    "id_Menu": "m_020"
  },
  {
    "id_Type": "t_004",
    "id_Meat": "m_001",
    "chinese_Name": "黄焖猪蹄",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1rTsQ5Px67BjojEV9TcOXWFA3MsUmzfkb",
    "id_Menu": "m_021"
  },
  {
    "id_Type": "t_009",
    "id_Meat": "m_009",
    "chinese_Name": "香蕉薄饼",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1Z8a0Fx205gp1RBy-gIKWB3s4os1EnxW2",
    "id_Menu": "m_022"
  },
  {
    "id_Type": "t_009",
    "id_Meat": "m_009",
    "chinese_Name": "椰奶煎饼",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1cA_OV5sLP7lvt21wdSDmGBYuVXXe6WVR",
    "id_Menu": "m_023"
  },
  {
    "id_Type": "t_009",
    "id_Meat": "m_009",
    "chinese_Name": "椰子布丁",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1NtxeFX3NixFVErgrxxKg8Ciqu2Ta6crD",
    "id_Menu": "m_024"
  },
  {
    "id_Type": "t_005",
    "id_Meat": "m_006",
    "chinese_Name": "泰式咖哩螃蟹",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=15A6f9LVZPHWKxmL7QYV5_ZhJQaRW7cNY",
    "id_Menu": "m_025"
  },
  {
    "id_Type": "t_003",
    "id_Meat": "m_007",
    "chinese_Name": "生蚝沙拉",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=12uEHHdNbhuUIP59FiJYn6cPkeL4_Nbzn",
    "id_Menu": "m_026"
  },
  {
    "id_Type": "t_009",
    "id_Meat": "m_009",
    "chinese_Name": "椰汁香兰糕",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1CSv9GHG-4GHazxweHPERQgND9X2l9dWZ",
    "id_Menu": "m_027"
  },
  {
    "id_Type": "t_006",
    "id_Meat": "m_008",
    "chinese_Name": "烤鱿鱼",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1SupKLG-nNLlEFDRXP19U33gs1dQte32J",
    "id_Menu": "m_028"
  },
  {
    "id_Type": "t_004",
    "id_Meat": "m_009",
    "chinese_Name": "竹筒糯米饭",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1p5krcHqD6M8fDvy4BipZJXrSZEHGSEV5",
    "id_Menu": "m_029"
  },
  {
    "id_Type": "t_006",
    "id_Meat": "m_004",
    "chinese_Name": "泰国烤虾",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=18txW_MAqkGBmKrVvaWBMlznyyTzLNpcq",
    "id_Menu": "m_030"
  },
  {
    "id_Type": "t_001",
    "id_Meat": "m_002",
    "chinese_Name": "白冬炎功汤",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "No",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1D3LcXgffXXDuiyYJ0I-PsWXUz0U1Fq7A",
    "id_Menu": "m_031"
  },
  {
    "id_Type": "t_002",
    "id_Meat": "m_009",
    "chinese_Name": "鸭面",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1apDmnLf6r0folLsvAl1oY14W7xaWXxqb",
    "id_Menu": "m_032"
  },
  {
    "id_Type": "t_009",
    "id_Meat": "m_009",
    "chinese_Name": "椰丝豆仁软糕",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1R4OWqsVUEjVtOruQe7GT5HaNWlXYO16z",
    "id_Menu": "m_033"
  },
  {
    "id_Type": "t_002",
    "id_Meat": "m_001",
    "chinese_Name": "船面",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1CF7XJfhwbMtc3UmrwXhpWfwMe2UKVgdP",
    "id_Menu": "m_034"
  },
  {
    "id_Type": "t_009",
    "id_Meat": "m_004",
    "chinese_Name": "泰式炸春卷",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1KtwwHIUr0dw3u3nuPeEFIfhAdNdCugCc",
    "id_Menu": "m_035"
  },
  {
    "id_Type": "t_011",
    "id_Meat": "m_009",
    "chinese_Name": "仿真迷你水果",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1XVe3_CafPmNLN-p8NOlwVarFXRJ_H7En",
    "id_Menu": "m_036"
  },
  {
    "id_Type": "t_005",
    "id_Meat": "m_004",
    "chinese_Name": "蒸咖哩鱼",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=188_hPZdzsZmy_YN6FtFG9_LbcCIZIqpf",
    "id_Menu": "m_037"
  },
  {
    "id_Type": "t_004",
    "id_Meat": "m_001",
    "chinese_Name": "泰式打抛猪肉饭",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1fLieV9uNzmhDkGud0_dtvfNp-9vbDc5w",
    "id_Menu": "m_038"
  },
  {
    "id_Type": "t_004",
    "id_Meat": "m_006",
    "chinese_Name": "蟹肉煎蛋",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1ui-gDI_NwA1NL42nZWatCaVxfoAzYGMh",
    "id_Menu": "m_039"
  },
  {
    "id_Type": "t_005",
    "id_Meat": "m_009",
    "chinese_Name": "咖喱芝士锔山药",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1XDDq11ET1TMvWAdCdXMa-3FC8vjhZ2OR",
    "id_Menu": "m_040"
  },
  {
    "id_Type": "t_005",
    "id_Meat": "m_003",
    "chinese_Name": "咖喱牛肉",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1wzkazkwKoemNJBmzc3bOXeGCMrq0-QrW",
    "id_Menu": "m_041"
  },
  {
    "id_Type": "t_004",
    "id_Meat": "m_009",
    "chinese_Name": "芒果糯米饭",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1Dr5Qu-qFODKNNB798WhjtxXrJM05byUS",
    "id_Menu": "m_042"
  },
  {
    "id_Type": "t_011",
    "id_Meat": "m_009",
    "chinese_Name": "芒果糯米饭",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1iSjYjcSBZbdfRGXiUBcclXYZOoUCOAqG",
    "id_Menu": "m_043"
  },
  {
    "id_Type": "t_001",
    "id_Meat": "m_002",
    "chinese_Name": "椰汁鸡汤",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1xInR4bdjXpiBocCWwRqaQCNEd-ism754",
    "id_Menu": "m_044"
  },
  {
    "id_Type": "t_005",
    "id_Meat": "m_003",
    "chinese_Name": "咖喱牛肉饭",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1D7FqSnJiB39L2q-1bIgCBAwl6vV_lneZ",
    "id_Menu": "m_045"
  },
  {
    "id_Type": "t_007",
    "id_Meat": "m_002",
    "chinese_Name": "腰果肌肉",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=14r7nGJ9RchSh3E2adoLYrTGxXlmDyNfN",
    "id_Menu": "m_046"
  },
  {
    "id_Type": "t_007",
    "id_Meat": "m_002",
    "chinese_Name": "腰果鸡肉",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1Tc0sLbFR7Vv4l4KB-GjAYqpG66eXQlGg",
    "id_Menu": "m_047"
  },
  {
    "id_Type": "t_004",
    "id_Meat": "m_009",
    "chinese_Name": "鸡蛋饭",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1N8zMxxTX5HQLpfHQ5rIBm-SUgZSqUlVI",
    "id_Menu": "m_048"
  },
  {
    "id_Type": "t_001",
    "id_Meat": "m_002",
    "chinese_Name": "绿咖喱鸡",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "very spicy",
    "picture": "https://drive.google.com/open?id=1LHVC78s0Eg0nsyY19u4dd3Eq6wNn8Vs3",
    "id_Menu": "m_049"
  },
  {
    "id_Type": "t_005",
    "id_Meat": "m_006",
    "chinese_Name": "泰式皇炒蟹",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1gAlB83nPMWBc6-RTPr1NBsSutN2__Jxw",
    "id_Menu": "m_050"
  },
  {
    "id_Type": "t_005",
    "id_Meat": "m_003",
    "chinese_Name": "马沙文咖喱",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1owXVUYBntNJzx6xkPGQsuQb381uoxLQ2",
    "id_Menu": "m_051"
  },
  {
    "id_Type": "t_008",
    "id_Meat": "m_002",
    "chinese_Name": "泰国炸鸡",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1XKb7YdeuPtjeR3tVUmkubul-vXD3P9R8",
    "id_Menu": "m_052"
  },
  {
    "id_Type": "t_008",
    "id_Meat": "m_004",
    "chinese_Name": "盐烤泰国虾",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1QnqihlluTGkxpw9BT1nO45M7VFiIozFv",
    "id_Menu": "m_053"
  },
  {
    "id_Type": "t_004",
    "id_Meat": "m_001",
    "chinese_Name": "猪脚饭",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1QLZt-owmbwIsyUNLDmgbXswVjw8SjFC0",
    "id_Menu": "m_054"
  },
  {
    "id_Type": "t_010",
    "id_Meat": "m_009",
    "chinese_Name": "泰式奶茶",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1uCRbHl3S6qsGzWJaTgqGWkqvijT3lZpO",
    "id_Menu": "m_055"
  },
  {
    "id_Type": "t_009",
    "id_Meat": "m_009",
    "chinese_Name": "泰式榴莲煎饼",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1Lt0RX-WaGTj3qrSIOLdPElIT_Y2u-RV3",
    "id_Menu": "m_056"
  },
  {
    "id_Type": "t_002",
    "id_Meat": "m_002",
    "chinese_Name": "泰式鸡肉面",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1vE8XojU8t5iS77MEBV4S18WIfLFvnrsa",
    "id_Menu": "m_057"
  },
  {
    "id_Type": "t_007",
    "id_Meat": "m_002",
    "chinese_Name": "九层塔炒鸡肉",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1Jw_MjuM6WNAWy40aLAQM7daIoUfGLWIy",
    "id_Menu": "m_058"
  },
  {
    "id_Type": "t_007",
    "id_Meat": "m_006",
    "chinese_Name": "咖喱蟹膏",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1GS4sBeJiXwRWJubVVWnvZFnk42mbYpsP",
    "id_Menu": "m_059"
  },
  {
    "id_Type": "t_007",
    "id_Meat": "m_001",
    "chinese_Name": "泰式炒酸辣猪颈肉",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1tCM2bjwrK4XpdA0WcK3uwwt9GCqm6BJk",
    "id_Menu": "m_060"
  },
  {
    "id_Type": "t_001",
    "id_Meat": "m_002",
    "chinese_Name": "椰汁鸡汤",
    "english_Name": "Coconut milk chicken soup",
    "thai_Name": "ซุปไก่มะพร้าว",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1e_jc9i_2BVImi2N734jteZ_lATPTKZUP",
    "id_Menu": "m_061"
  },
  {
    "id_Type": "t_002",
    "id_Meat": "m_004",
    "chinese_Name": "鱼蛋粉",
    "english_Name": "Fish egg powder",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1hInumcJ0GMlTzWyy4h3lQ_4n6vyeOj6t",
    "id_Menu": "m_062"
  },
  {
    "id_Type": "t_004",
    "id_Meat": "m_009",
    "chinese_Name": "泰式菠萝饭",
    "english_Name": "Thai pineapple rice",
    "thai_Name": "ข้าวสับปะรด",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1sAGj9wdrGjlZShkm3U0L7m3wVIryBdXX",
    "id_Menu": "m_063"
  },
  {
    "id_Type": "t_004",
    "id_Meat": "m_002",
    "chinese_Name": "海南鸡饭",
    "english_Name": "Chicken Rice, Hainan Style",
    "thai_Name": "ข้าวไก่ไห่หนาน",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1shB8_CYKpxYTgxeqY0160FuJGsD0c13m",
    "id_Menu": "m_064"
  },
  {
    "id_Type": "t_004",
    "id_Meat": "m_001",
    "chinese_Name": "罗勒叶炒猪肉饭",
    "english_Name": "Fried pork with basil leaf",
    "thai_Name": "ข้าวหมูผัดกะเพรา",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1cMLSzHFWWTdtadmrfMqk5zBZh-WTImMA",
    "id_Menu": "m_065"
  },
  {
    "id_Type": "t_007",
    "id_Meat": "m_004",
    "chinese_Name": "柠檬蒸鲈鱼",
    "english_Name": "Steamed perch with lemon",
    "thai_Name": "ปลาแมคเคอเรล",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1_gleFpwfzW-WcdkB_11arlt0UGZeHz3M",
    "id_Menu": "m_066"
  },
  {
    "id_Type": "t_005",
    "id_Meat": "m_004",
    "chinese_Name": "咖喱鱼饼",
    "english_Name": "Curry Fish Cake",
    "thai_Name": "แกง fishcakes",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1f-YdW55ZagYNvbMiNbdMetMXlbF4sa26",
    "id_Menu": "m_067"
  },
  {
    "id_Type": "t_007",
    "id_Meat": "m_002",
    "chinese_Name": "九层塔炒鸡",
    "english_Name": "Fried chicken with nine story pagoda",
    "thai_Name": "ทาวเวอร์เก้าเนื้อไก่ทอด",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1wIFo9P9zDnZcBpS6hYVEvhgELdsRFXPd",
    "id_Menu": "m_068"
  },
  {
    "id_Type": "t_002",
    "id_Meat": "m_003",
    "chinese_Name": "牛肉米",
    "english_Name": "Beef rice noodle",
    "thai_Name": "สายข้าวเนื้อ",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1FMIY0XuF9sgg0OqO3W8LVhhGvo0Rsbkt",
    "id_Menu": "m_069"
  },
  {
    "id_Type": "t_002",
    "id_Meat": "m_004",
    "chinese_Name": "炒金边粉",
    "english_Name": "Fried Phnom Penh powder",
    "thai_Name": "พนมเปญผง",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1lzTd5Mt8vblfUKBwFENL0nZU54qGFKC6",
    "id_Menu": "m_070"
  },
  {
    "id_Type": "t_009",
    "id_Meat": "m_009",
    "chinese_Name": "椰子冰淇淋",
    "english_Name": "Coconut Ice Cream",
    "thai_Name": "ไอศกรีมมะพร้าว",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1EoM8d_tNx3_S3nNdQQmJQiiTvQuMjyzz",
    "id_Menu": "m_071"
  },
  {
    "id_Type": "t_009",
    "id_Meat": "m_009",
    "chinese_Name": "椰汁西米糕",
    "english_Name": "Coconut Pudding",
    "thai_Name": "Simecake มะพร้า",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=18nStDvpwpEtTCN3Pz9Zy4PA3gxvBYkdR",
    "id_Menu": "m_072"
  },
  {
    "id_Type": "t_009",
    "id_Meat": "m_009",
    "chinese_Name": "碧绿千层糕",
    "english_Name": "Green cake",
    "thai_Name": "เค้กสีเทอร์ควอยซ์พันชั้น",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=129wOUfZv6IIADovAuL6WBjI5DBUnzR6b",
    "id_Menu": "m_073"
  },
  {
    "id_Type": "t_009",
    "id_Meat": "m_009",
    "chinese_Name": "糖丝春卷",
    "english_Name": "Sugar spring rolls",
    "thai_Name": "ปอเปี๊ยะไหมน้ำตาล",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1unhdpZ-LwyOJvji0t9yajpOAUZzrJFES",
    "id_Menu": "m_074"
  },
  {
    "id_Type": "t_009",
    "id_Meat": "m_009",
    "chinese_Name": "椰奶小脆饼",
    "english_Name": "Coconut milk crispy cake",
    "thai_Name": "น้ำกะทิ",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1ARehhBKMLQQ8lWDZpVmLOdXS5QQVYyHp",
    "id_Menu": "m_075"
  },
  {
    "id_Type": "t_009",
    "id_Meat": "m_009",
    "chinese_Name": "泰式珍珠丸子",
    "english_Name": "Thai Pearl Balls",
    "thai_Name": "ไทยเพิร์ลเม็ด",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1n_sbUfd6WxWZ54ejDScW9izHMdD1Aher",
    "id_Menu": "m_076"
  },
  {
    "id_Type": "t_009",
    "id_Meat": "m_009",
    "chinese_Name": "浆米粉糕",
    "english_Name": "Rice noodles cake",
    "thai_Name": "เค้กข้าวเยื่อ",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1PWtVdtnrkmlWASdzMFES9Eg6zIs4yGf1",
    "id_Menu": "m_077"
  },
  {
    "id_Type": "t_008",
    "id_Meat": "m_009",
    "chinese_Name": "榴莲煎饼",
    "english_Name": "",
    "thai_Name": "แพนเค้กทุเรียน",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1wEp8xjMC6OhcCq_LfzrV4KP5IUCMP6Lb",
    "id_Menu": "m_078"
  },
  {
    "id_Type": "t_007",
    "id_Meat": "m_001",
    "chinese_Name": "炒酸辣猪颈肉",
    "english_Name": "",
    "thai_Name": "คอหมูผัดเผ็ด",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1jkHdX4Nc3OoZpypcvP3esrHaKojSTCmM",
    "id_Menu": "m_079"
  },
  {
    "id_Type": "t_010",
    "id_Meat": "m_009",
    "chinese_Name": "泰式奶茶",
    "english_Name": "",
    "thai_Name": "ชานม",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1VDvjOzGU0X-ysbybs-DJOt9IcWR4YXzQ",
    "id_Menu": "m_080"
  },
  {
    "id_Type": "t_005",
    "id_Meat": "m_002",
    "chinese_Name": "咖喱鸡肉",
    "english_Name": "",
    "thai_Name": "แกงกะหรี่ไก่",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1850zciau65ASET9q-hbPSGuwIoSmFc1O",
    "id_Menu": "m_081"
  },
  {
    "id_Type": "t_005",
    "id_Meat": "m_006",
    "chinese_Name": "咖喱蟹膏",
    "english_Name": "",
    "thai_Name": "แกงปู",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1u3nbPlYEU7e22hvLeRtoBjBf5q2nqV0B",
    "id_Menu": "m_082"
  },
  {
    "id_Type": "t_008",
    "id_Meat": "m_002",
    "chinese_Name": "泰式香煎麻椒鸡",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1V37yLWaIE-WURHz4AsoNJXdol0Rv6zxn",
    "id_Menu": "m_083"
  },
  {
    "id_Type": "t_012",
    "id_Meat": "m_004",
    "chinese_Name": "红鲷鱼",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1YE8siqo3MVyHKyaZ6-JiWi1E3sB9bX-S",
    "id_Menu": "m_084"
  },
  {
    "id_Type": "t_002",
    "id_Meat": "m_002",
    "chinese_Name": "面条鸡肉和蔬菜",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1eTo2KK0_O0cLwOzPJgnowrt-kvn17Ppl",
    "id_Menu": "m_085"
  },
  {
    "id_Type": "t_004",
    "id_Meat": "m_001",
    "chinese_Name": "米饭配上炒肉末",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1cYhP_B_CRb4NcWzw2S6-S0A0i6hz4Ata",
    "id_Menu": "m_086"
  },
  {
    "id_Type": "t_005",
    "id_Meat": "m_004",
    "chinese_Name": "虾在咖喱酱和米饭",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=13RlyTMJ-QZMhLwFezxj2WAp6_pgahF-F",
    "id_Menu": "m_087"
  },
  {
    "id_Type": "t_005",
    "id_Meat": "m_003",
    "chinese_Name": "牛肉马萨曼咖喱",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=1pl1DoY0eXurm2_ViF85LzMk5cRJL51FV",
    "id_Menu": "m_088"
  },
  {
    "id_Type": "t_003",
    "id_Meat": "m_004",
    "chinese_Name": "辣海鲜沙拉",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "No",
    "spiciness": "little spicy",
    "picture": "https://drive.google.com/open?id=16oxerlOPBLLGTASgiH-2eddcLK1E72ml",
    "id_Menu": "m_089"
  },
  {
    "id_Type": "t_012",
    "id_Meat": "m_009",
    "chinese_Name": "馅薄饼或煎面包",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1Sr3LeQOCXS2Ki5Zi1JcKCBZAPqsnc0oF",
    "id_Menu": "m_090"
  },
  {
    "id_Type": "t_006",
    "id_Meat": "m_004",
    "chinese_Name": "烤三文鱼",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=16J8j62vewRg6_ZrsnZjvxNz7YhOzMFxG",
    "id_Menu": "m_091"
  },
  {
    "id_Type": "t_012",
    "id_Meat": "m_004",
    "chinese_Name": "辣金枪鱼",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "very spicy",
    "picture": "https://drive.google.com/open?id=11L3bwtOCqhxoOjV2cxZXytcVub6KSCyx",
    "id_Menu": "m_092"
  },
  {
    "id_Type": "t_003",
    "id_Meat": "m_009",
    "chinese_Name": "玉米番木瓜沙拉",
    "english_Name": "",
    "thai_Name": "",
    "recommend": "Yes",
    "spiciness": "no spicy",
    "picture": "https://drive.google.com/open?id=1qBCA8Thyu7UmTS9aMrbTB-8pkJwfqt4N",
    "id_Menu": "m_093"
  }
]

menu.forEach(function(obj) {
  db.collection("menu").add({
    id_Menu:obj.id_Menu,
    chinese_Name: obj.chinese_Name,
    english_Name: obj.english_Name,
    thai_Name:obj.thai_Name,
    recommend:obj.recommend,
    spiciness:obj.spiciness,
    id_Type: obj.id_Type,
    id_Meat: obj.id_Meat,
    picture: obj.picture
    }).then(function(docRef) {
      console.log("Document written with ID: ", docRef.id);
  })
  .catch(function(error) {
      console.error("Error adding document: ", error);
  });
})
